[package]
name = "telegrand"
version = "0.1.0"
authors = ["Marco Melorio <marco.melorio@protonmail.com>"]
edition = "2018"

[dependencies]
adw = { package = "libadwaita", git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs" }
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session = { git = "https://github.com/Lonami/grammers" }
gtk = { package = "gtk4", git = "https://github.com/gtk-rs/gtk4-rs" }
gtk-macros = "0.2"
log = "0.4.11"
once_cell = "1.5"
simple_logger = "1.11.0"
tokio = { version = "1.0.1", features = ["rt"] }
